### ISSUE TITLE
Unable to compile cdapc (rina-tools) with protobuf 3.0

### ISSUE THREAD

**Issue by vmaffione** [IRATI/stack#1048]
Problem showed up in Archlinux after the upgrade of the protobuf package from 2.6.1 to 3.0.2.

````
/bin/sh ../../libtool  --tag=CXX   --mode=link g++  -g -O2   -o cdapc cdapc-main.o cdapc-connector.o cdapc-easywsclient.o cdapc-dmsworker.o cdapc-maworker.o cdapc-eventfilters.o cdapc-json_format.o -L/home/vmaffione/git/nxw/irati/local/lib -lrina -lnl-genl-3 -lnl-3 -lprotobuf -pthread -lpthread -ldl -lrinad -Lencoders -lfullencoders ../common/librinaapp.la	 
libtool: link: g++ -g -O2 -o cdapc cdapc-main.o cdapc-connector.o cdapc-easywsclient.o cdapc-dmsworker.o cdapc-maworker.o cdapc-eventfilters.o cdapc-json_format.o -pthread  -L/home/vmaffione/git/nxw/irati/local/lib /home/vmaffione/git/nxw/irati/local/lib/librinad.so -Lencoders /home/vmaffione/git/nxw/irati/build/rina-tools/src/cdapc/encoders/.libs/libfullencoders.a ../common/.libs/librinaapp.a /home/vmaffione/git/nxw/irati/local/lib/librina.so -lssl -lcrypto /home/vmaffione/git/nxw/irati/local/lib/librinajsoncpp.so -ldl -lnl-genl-3 -lnl-3 -lprotobuf -lpthread -pthread -Wl,-rpath -Wl,/home/vmaffione/git/nxw/irati/local/lib -Wl,-rpath -Wl,/home/vmaffione/git/nxw/irati/local/lib
cdapc-json_format.o: In function `google::protobuf::safe_strto32(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int*)':
/home/vmaffione/git/nxw/irati/rina-tools/src/cdapc/strutil.h:357: undefined reference to `google::protobuf::safe_int(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int*)'
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:777: cdapc] Error 1
make[5]: Leaving directory '/home/vmaffione/git/nxw/irati/build/rina-tools/src/cdapc'
make[4]: *** [Makefile:1094: all-recursive] Error 1
make[4]: Leaving directory '/home/vmaffione/git/nxw/irati/build/rina-tools/src/cdapc'
make[3]: *** [Makefile:579: all-recursive] Error 1
make[3]: Leaving directory '/home/vmaffione/git/nxw/irati/build/rina-tools/src'
make[2]: *** [Makefile:403: all] Error 2
make[2]: Leaving directory '/home/vmaffione/git/nxw/irati/build/rina-tools/src'
make[1]: *** [Makefile:441: all-recursive] Error 1
make[1]: Leaving directory '/home/vmaffione/git/nxw/irati/build/rina-tools'
make: *** [Makefile:388: all] Error 2
install-user-from-scratch: Cannot complete rina-tools phase

````

**Comment by edugrasa** [comment]
Fixed by #1170
